/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ShippingAddressInput = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'fullName' : IDL.Text,
  'state' : IDL.Text,
  'streetAddress' : IDL.Text,
});
export const AddressId = IDL.Text;
export const ShippingAddress = IDL.Record({
  'id' : AddressId,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'fullName' : IDL.Text,
  'state' : IDL.Text,
  'isDefault' : IDL.Bool,
  'streetAddress' : IDL.Text,
});
export const ProductId = IDL.Text;
export const LineItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const OrderId = IDL.Text;
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'userId' : IDL.Opt(IDL.Principal),
  'timestamp' : Timestamp,
  'items' : IDL.Vec(LineItem),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addShippingAddress' : IDL.Func(
      [ShippingAddressInput],
      [IDL.Variant({ 'ok' : ShippingAddress, 'err' : IDL.Text })],
      [],
    ),
  'addToWishlist' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(LineItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteShippingAddress' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserShippingAddresses' : IDL.Func([], [IDL.Vec(ShippingAddress)], []),
  'getUserWishlist' : IDL.Func([], [IDL.Vec(Product)], []),
  'isProductInWishlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromWishlist' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setDefaultShippingAddress' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateShippingAddress' : IDL.Func(
      [IDL.Text, ShippingAddressInput],
      [IDL.Variant({ 'ok' : ShippingAddress, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ShippingAddressInput = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'fullName' : IDL.Text,
    'state' : IDL.Text,
    'streetAddress' : IDL.Text,
  });
  const AddressId = IDL.Text;
  const ShippingAddress = IDL.Record({
    'id' : AddressId,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'fullName' : IDL.Text,
    'state' : IDL.Text,
    'isDefault' : IDL.Bool,
    'streetAddress' : IDL.Text,
  });
  const ProductId = IDL.Text;
  const LineItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const OrderId = IDL.Text;
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'userId' : IDL.Opt(IDL.Principal),
    'timestamp' : Timestamp,
    'items' : IDL.Vec(LineItem),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addShippingAddress' : IDL.Func(
        [ShippingAddressInput],
        [IDL.Variant({ 'ok' : ShippingAddress, 'err' : IDL.Text })],
        [],
      ),
    'addToWishlist' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(LineItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteShippingAddress' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserShippingAddresses' : IDL.Func([], [IDL.Vec(ShippingAddress)], []),
    'getUserWishlist' : IDL.Func([], [IDL.Vec(Product)], []),
    'isProductInWishlist' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromWishlist' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setDefaultShippingAddress' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateShippingAddress' : IDL.Func(
        [IDL.Text, ShippingAddressInput],
        [IDL.Variant({ 'ok' : ShippingAddress, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };