/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AddressId = string;
export interface LineItem { 'productId' : ProductId, 'quantity' : bigint }
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : bigint,
  'userId' : [] | [Principal],
  'timestamp' : Timestamp,
  'items' : Array<LineItem>,
}
export type OrderId = string;
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export interface Product {
  'id' : ProductId,
  'featured' : boolean,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'imageUrl' : string,
  'price' : bigint,
}
export type ProductId = string;
export interface ShippingAddress {
  'id' : AddressId,
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'fullName' : string,
  'state' : string,
  'isDefault' : boolean,
  'streetAddress' : string,
}
export interface ShippingAddressInput {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'fullName' : string,
  'state' : string,
  'streetAddress' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addShippingAddress' : ActorMethod<
    [ShippingAddressInput],
    { 'ok' : ShippingAddress } |
      { 'err' : string }
  >,
  'addToWishlist' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'createCheckoutSession' : ActorMethod<
    [Array<LineItem>, string, string],
    string
  >,
  'deleteShippingAddress' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserShippingAddresses' : ActorMethod<[], Array<ShippingAddress>>,
  'getUserWishlist' : ActorMethod<[], Array<Product>>,
  'isProductInWishlist' : ActorMethod<[string], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeFromWishlist' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setDefaultShippingAddress' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateShippingAddress' : ActorMethod<
    [string, ShippingAddressInput],
    { 'ok' : ShippingAddress } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];